### Методом Північно-західного кута

In [1]:
import numpy as np

def my_northwest_corner_method(supply, demand, costs):
    result_matrix = np.zeros((len(supply), len(demand)))

    i, j = 0, 0

    while i < len(supply) and j < len(demand):
        quantity = min(supply[i], demand[j])

        result_matrix[i, j] = quantity

        supply[i] -= quantity
        demand[j] -= quantity

        if supply[i] == 0:
            i += 1
        else:
            j += 1

    return result_matrix

def calculate_total_cost(result_matrix, costs):
    total_cost = np.sum(result_matrix * costs)
    return total_cost

In [2]:
s = [230, 250, 170] 
d = [140,    90,    160,    110,    150] 
c = np.array([
[40,    19,    25,    25,    35],
[49,    26,    27,    18,    38],
[49,    27,    36,    40,    45]])

matrix = my_northwest_corner_method(s, d, c)
print("Матриця відповідей:\n")
print(matrix)

total_cost = calculate_total_cost(matrix, c)
print("\nЗагальна ціна перевезень:", total_cost)

Матриця відповідей:

[[140.  90.   0.   0.   0.]
 [  0.   0. 160.  90.   0.]
 [  0.   0.   0.  20. 150.]]

Загальна ціна перевезень: 20800.0


#### Значення з excel збігаються

### Транспортна проблема з потенціалами

In [8]:
from pulp import LpProblem, LpVariable, lpSum, LpMinimize

supply2 = [200, 350, 300]
demand2 = [270, 130, 190, 150, 110]
costs2 = [
    [24, 50, 5, 27, 16],
    [50, 47, 23, 17, 21],
    [35, 59, 55, 27, 41]
]

prob = LpProblem("Transportation_Problem", LpMinimize)

routes = [(i, j) for i in range(len(supply2)) for j in range(len(demand2))]
x = LpVariable.dicts("X", routes, lowBound=0, cat="Integer")

prob += lpSum(x[i, j] * costs2[i][j] for i in range(len(supply2)) for j in range(len(demand2)))

for i in range(len(supply2)):
    prob += lpSum(x[i, j] for j in range(len(demand2))) == supply2[i]

for j in range(len(demand2)):
    prob += lpSum(x[i, j] for i in range(len(supply2))) == demand2[j]

prob.solve()

# Вивід результатів готовою бібліотекою
print("Статус:", prob.status)
print("Оптимальне значення (ціна):", round(prob.objective.value(), 2))

# Виходить така матриця рішень
for i in range(len(supply2)):
    for j in range(len(demand2)):
        if x[i, j].value() > 0:
            print(f"Доставити {x[i, j].value()} товару з сховища {i + 1} до запиту {j + 1}")


Статус: 1
Оптимальне значення (ціна): 21620
Доставити 190 товару з сховища 1 до запиту 3
Доставити 10 товару з сховища 1 до запиту 5
Доставити 130 товару з сховища 2 до запиту 2
Доставити 120 товару з сховища 2 до запиту 4
Доставити 100 товару з сховища 2 до запиту 5
Доставити 270 товару з сховища 3 до запиту 1
Доставити 30 товару з сховища 3 до запиту 4
