In [48]:
import numpy as np

k = 3

values = np.array([[180, 140, k, 245 - 4*k, 232],
                   [420, 120 + 10*k, 140, 220, 100],
                   [25 + 8*k, 315, 35, 49, 10 * (k+23) - 50],
                   [290 - 10*k, k, 9, 100*k -90, 201]])

alpha = 1 / (k + 3) if(1 <= k <= 12) else 4/k 

print("λ: ", alpha)

p = np.array([0.1, 0.2, alpha, alpha + 0.1, 0.6 - 2*alpha])

print("\np: ", p)
print("\nValues:\n", values)


λ:  0.16666666666666666

p:  [0.1        0.2        0.16666667 0.26666667 0.26666667]

Values:
 [[180 140   3 233 232]
 [420 150 140 220 100]
 [ 49 315  35  49 210]
 [260   3   9 210 201]]


## Оптимізм

In [49]:
optMaxValues = np.max(values, 1)

print("Результати для оптимізму", optMaxValues)
print("Найкращий варіант", np.argmin(optMaxValues)+1)

Результати для оптимізму [233 420 315 260]
Найкращий варіант 1


## Песимізм

In [50]:
pesMinValues = np.min(values, 1)

print("Результати для песимізму", pesMinValues)
print("Найкращий варіант", np.argmax(pesMinValues)+1)


Результати для песимізму [  3 100  35   3]
Найкращий варіант 2


## Використовуючи формулу Гурвіца

In [51]:
hurvitsValues = np.min(values,1) * alpha + (1-alpha) * np.max(values,1)

print("Результати за Гурвіцом", hurvitsValues)
print("Найкращий варіант", np.argmax(hurvitsValues)+1)

Результати за Гурвіцом [194.66666667 366.66666667 268.33333333 217.16666667]
Найкращий варіант 2


## Використовуючи формулу Лапласа

In [52]:
laplasValues = np.average(values, 1)

print("Результати за Лапласом", laplasValues)
print("Найкращий варіант", np.argmax(laplasValues)+1)

Результати за Лапласом [157.6 206.  131.6 136.6]
Найкращий варіант 2


## Використовуючи формулу Баєс-Лапласа

In [53]:
bayesValues = np.sum(values * p, 1)

print("Результати за Баєсом-Лапласом", bayesValues)
print("Найкращий варіант", np.argmax(bayesValues)+1)

Результати за Баєсом-Лапласом [170.5        180.66666667 142.8        137.7       ]
Найкращий варіант 2


## Використовуючи формулу Ходж-Лемана

In [54]:
lemanValues = (1-alpha) * pesMinValues + bayesValues * alpha

print("Результати за Ходж-Леман", lemanValues)
print("Найкращий варіантт", np.argmax(lemanValues)+1)

Результати за Ходж-Леман [ 30.91666667 113.44444444  52.96666667  25.45      ]
Найкращий варіантт 2
